functionsDirectory = "C:\\Users\\johna\\Desktop\\Blue Iron\\Reports\\bic-field-reporter\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\johna\\Desktop\\Blue Iron\\Reports\\bic-field-reporter\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\johna\\Desktop\\Blue Iron\\Reports\\bic-field-reporter\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]